from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8-sig")


def write(rel: str, text: str) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    encoding = "utf-8-sig" if path.suffix.lower() in {".ps1", ".psm1"} else "utf-8"
    path.write_text(text, encoding=encoding)


def once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected 1 match, found {count}")
    return text.replace(old, new, 1)


readme = read("README.md")
readme = once(readme, "**Stable release: [v1.4.0]", "**Stable release: [v1.5.0]", "README version")
readme = once(
    readme,
    "- Three detection modes: generic `WindowsEndpoint`, `LogitechGHub` (PRO X / PRO X 2 / PRO X Wireless), `SteelSeriesNova5` (Arctis Nova 5 / 5X).\n- Tray controls for AutoSwitch, reconfiguration and Windows Audio Enhancements.\n",
    "- Three config modes remain backward compatible, with direct Centurion HID for Logitech PRO X 2 LIGHTSPEED (`046D:0AF7`) and the existing G HUB provider for other compatible Logitech headsets.\n- Tray controls for AutoSwitch, reconfiguration and Windows Audio Enhancements; PRO X 2 also shows live battery percentage and connection state.\n",
    "README headline",
)
readme = once(readme, "  - [LogitechGHub](#logitechghub)\n", "  - [Logitech PRO X 2 — Centurion HID](#logitech-pro-x-2--centurion-hid)\n  - [LogitechGHub](#logitechghub)\n", "README toc")
readme = once(
    readme,
    "| Any headset whose Windows endpoint exposes connection state | `WindowsEndpoint` | None | Validated with a Jabra Evolve 65. |\n| Logitech PRO X, PRO X 2, PRO X Wireless | `LogitechGHub` | Logitech G HUB (installed and running) | Used when Windows keeps the endpoint `Active` while the physical headset is off. |\n| SteelSeries Arctis Nova 5 / 5X | `SteelSeriesNova5` | None | Physical state read over HID; no SteelSeries GG required. |",
    "| Any headset whose Windows endpoint exposes connection state | `WindowsEndpoint` | None | Validated with a Jabra Evolve 65. |\n| Logitech PRO X 2 LIGHTSPEED (`046D:0AF7`) | `LogitechGHub` (backward-compatible config name) | None for state detection | v1.5.0 reads the LIGHTSPEED receiver directly through Centurion HID and reports battery in the tray. |\n| Other compatible Logitech headsets (including PRO X / PRO X Wireless) | `LogitechGHub` | Logitech G HUB (installed and running) | Keeps the existing local WebSocket battery provider. |\n| SteelSeries Arctis Nova 5 / 5X | `SteelSeriesNova5` | None | Physical state read over HID; no SteelSeries GG required. |",
    "README support table",
)
pattern = re.compile(r"### LogitechGHub\n\nThe Logitech PRO X family.*?The G HUB interface is unofficial and may change in a future G HUB release\. See \[`SOURCES\.md`\]\(SOURCES\.md\) and \[`AGENT\.md`\]\(AGENT\.md\) for the verified design notes\.\n", re.S)
match = pattern.search(readme)
if not match:
    raise SystemExit("README Logitech section not found")
new_section = '''### Logitech PRO X 2 — Centurion HID\n\nStarting with v1.5.0, Logitech PRO X 2 LIGHTSPEED no longer depends on G HUB's `/battery/<deviceId>/state` route for physical ON/OFF detection. G HUB 2026.5.939708 was observed returning `NO_SUCH_PATH` for that route while `/devices/list` continued to report the receiver as `ACTIVE` even when the headset was physically off.\n\nAutoSwitch now talks directly to the PRO X 2 LIGHTSPEED receiver:\n\n```text\nPRO X 2 LIGHTSPEED receiver (VID 046D / PID 0AF7)\n  ↓\nvendor HID collection · UsagePage 0xFFA0 · 64-byte Centurion frames\n  ↓\nvalid battery response → Connected + battery %\nknown power/off signature → Disconnected\nanything else → Unknown → no switch\n  ↓\ntwo OFF observations → fallback\nvalid ON response → headset\n```\n\nThe same battery value is exposed in the tray, for example `Battery: 76%`. The config continues to use `DetectionMode = LogitechGHub` for backward compatibility with existing installs, but the runtime automatically selects the direct Centurion provider for PRO X 2.\n\nThe direct provider was validated on real hardware on 2026-08-31 across repeated `ON → OFF → ON` cycles while G HUB was still running.\n\n### LogitechGHub\n\nOther compatible Logitech headsets still use the existing G HUB local WebSocket provider when Windows keeps their endpoint `Active` while the physical headset is off:\n\n```text\ncompatible Logitech headset\n  ↓\nLogitech G HUB · ws://localhost:9010\n  ↓\nGET /devices/list\nGET /battery/<deviceId>/state\n  ↓\npayload present → ON\npayload absent  → OFF\n```\n\nThe G HUB interface is unofficial and may change in a future G HUB release. PRO X 2 was moved to direct HID specifically to avoid relying on the route that changed in G HUB 2026.5.939708. See [`SOURCES.md`](SOURCES.md) and [`AGENT.md`](AGENT.md) for the verified design notes.\n'''
readme = readme[:match.start()] + new_section + readme[match.end():]
readme = readme.replace("| `DetectionMode` | set by installer | `WindowsEndpoint`, `LogitechGHub` or `SteelSeriesNova5`. |", "| `DetectionMode` | set by installer | `WindowsEndpoint`, `LogitechGHub` or `SteelSeriesNova5`. PRO X 2 keeps `LogitechGHub` as a backward-compatible config value but uses direct Centurion HID in v1.5.0. |")
readme = once(readme, "The tray menu shows the configured headset, fallback and next switch action.\n", "The tray menu shows the configured headset, fallback and next switch action. For PRO X 2 LIGHTSPEED it also shows direct HID connection state and live battery percentage.\n", "README tray")
readme = readme.replace("- **Logitech headset is on but the output stays on the speakers.** The G HUB WebSocket is the physical-state signal. Make sure Logitech G HUB is installed and running, then rerun the validation wizard.", "- **PRO X 2 stopped switching after a G HUB update.** Upgrade to v1.5.0 or newer. PRO X 2 now uses direct Centurion HID and no longer depends on G HUB's removed battery route. Run `Verify.cmd` to see the direct state and battery.\n- **Another Logitech headset is on but the output stays on the speakers.** Its G HUB provider still needs Logitech G HUB installed and running; rerun the validation wizard.")
readme = readme.replace("- Logitech G HUB installed and running for `LogitechGHub` mode.", "- Logitech G HUB installed and running for Logitech headsets that still use the G HUB provider. PRO X 2 LIGHTSPEED direct state detection does not require the G HUB battery API.")
readme = readme.replace("- Falls back to Logitech G HUB only when Windows cannot expose a useful physical state and the selected headset is confirmed as a Logitech PRO X family device.", "- For PRO X 2 LIGHTSPEED, checks the direct Centurion HID receiver when Windows cannot expose a useful physical state; other compatible Logitech headsets can fall back to G HUB.")
readme = readme.replace("lib/AutoSwitchCore.psm1                        shared pure logic + COM interop\nlib/SteelSeriesNova5.psm1", "lib/AutoSwitchCore.psm1                        shared pure logic + COM interop\nlib/LogitechProX2Centurion.psm1                 direct PRO X 2 HID + battery provider\nlib/SteelSeriesNova5.psm1")
readme = readme.replace("- The G HUB WebSocket is local but unofficial; treat compatibility changes after G HUB updates as expected maintenance risk.", "- PRO X 2 state/battery is read locally from its HID receiver. The G HUB WebSocket remains local but unofficial for other Logitech providers; treat future compatibility changes as expected maintenance risk.")
write("README.md", readme)


changelog = read("CHANGELOG.md")
v15 = '''## [1.5.0] - 2026-08-31\n\n### Fixed\n- **Restored Logitech PRO X 2 LIGHTSPEED AutoSwitch after a G HUB API regression.** G HUB `2026.5.939708` was observed returning `NO_SUCH_PATH` for `GET /battery/<deviceId>/state`, while `/devices/list` kept the PRO X 2 receiver `ACTIVE` with `resourcesAvailable=true` even when the headset was physically off.\n- PRO X 2 now bypasses that G HUB battery route and reads the LIGHTSPEED receiver directly through Logitech's Centurion HID protocol (`VID 046D`, `PID 0AF7`, `UsagePage 0xFFA0`, 64-byte reports).\n- Direct HID was validated on real PRO X 2 hardware on 2026-08-31 with repeated real `ON → OFF → ON` cycles: valid battery frames selected the headset; two consecutive known OFF observations selected the configured fallback; returning ON selected the headset again.\n\n### Added\n- `lib/LogitechProX2Centurion.psm1`: isolated direct HID provider returning `Connected`, `Disconnected` or `Unknown`, plus `BatteryPercent`.\n- PRO X 2 battery percentage and physical connection state in the tray; the tooltip also includes battery while connected.\n- `tools/Test-LogitechProX2Centurion.ps1` for live direct-state/battery diagnostics.\n- Pester coverage for PRO X 2 provider/config selection and release-package integration.\n\n### Changed\n- Existing `DetectionMode = LogitechGHub` configs remain backward compatible. When the configured headset is a PRO X 2, the runtime automatically prefers direct Centurion HID; other compatible Logitech headsets keep the existing G HUB provider.\n- `Unknown` HID/open/read/protocol failures never switch audio. OFF still requires the configured consecutive-read debounce before the fallback is selected.\n- Installer, verifier, README, English/Spanish Wiki source, website, maintainer notes, support/security notes, release tooling and package manifest were updated for v1.5.0.\n\n'''
changelog = once(changelog, "## [1.4.0] - 2026-08-13\n", v15 + "## [1.4.0] - 2026-08-13\n", "CHANGELOG")
write("CHANGELOG.md", changelog)


home = read("wiki/Home.md").replace("v1.4.0", "v1.5.0")
home = once(home, "**LogitechGHub** is the device-specific fallback for the Logitech PRO X family (PRO X, PRO X 2, PRO X Wireless), whose Windows endpoint can remain `Active` while the physical headset is off. AutoSwitch uses G HUB's unofficial local WebSocket as the signal.\n", "**Logitech PRO X 2 (v1.5.0)** keeps the backward-compatible `LogitechGHub` config value but now reads the LIGHTSPEED receiver directly through Centurion HID (`046D:0AF7`, UsagePage `0xFFA0`). This restores ON/OFF detection after G HUB 2026.5.939708 stopped exposing the old battery route, and it also provides live battery percentage in the tray.\n\n**LogitechGHub** remains the device-specific fallback for other compatible Logitech headsets such as PRO X / PRO X Wireless when Windows keeps the endpoint `Active` while the physical headset is off.\n", "Wiki Home")
write("wiki/Home.md", home)

inicio = read("wiki/Inicio.md").replace("v1.4.0", "v1.5.0")
inicio = once(inicio, "**LogitechGHub** es la salida alternativa específica para la familia Logitech PRO X (PRO X, PRO X 2, PRO X Wireless), cuyo endpoint de Windows puede seguir en `Active` aunque el auricular esté apagado. AutoSwitch usa el WebSocket local no oficial de G HUB como señal.\n", "**Logitech PRO X 2 (v1.5.0)** mantiene el valor de configuración compatible `LogitechGHub`, pero ahora lee directamente el receptor LIGHTSPEED mediante Centurion HID (`046D:0AF7`, UsagePage `0xFFA0`). Esto recupera la detección ON/OFF después de que G HUB 2026.5.939708 dejara de exponer la antigua ruta de batería y, además, muestra el porcentaje de batería en la bandeja.\n\n**LogitechGHub** sigue siendo el método alternativo para otros auriculares Logitech compatibles, como PRO X / PRO X Wireless, cuando Windows mantiene el endpoint en `Active` aunque el auricular esté apagado.\n", "Wiki Inicio")
write("wiki/Inicio.md", inicio)

for rel in ["wiki/How-It-Works.md", "wiki/Installation.md", "wiki/Tray-and-Reconfiguration.md", "wiki/Troubleshooting.md", "wiki/FAQ.md"]:
    if (ROOT.joinpath(rel).exists():
        text = read(rel).replace("v1.4.0", "v1.5.0")
        if "Centurion" not in text:
            text += "\n\n## PRO X 2 in v1.5.0\n\nLogitech PRO X 2 LIGHTSPEED uses direct Centurion HID for physical ON/OFF state and battery percentage. The configuration value remains `LogitechGHub` for backward compatibility, but G HUB's removed `/battery/<deviceId>/state` route is not used for PRO X 2 state detection anymore. Unknown HID reads never switch audio, and OFF still requires consecutive confirmed observations.\n"
        write(rel, text)
for rel in ["wiki/Como-funciona.md", "wiki/Instalacion.md", "wiki/Bandeja-y-reconfiguracion.md", "wiki/Resolucion-de-problemas.md", "wiki/FAQ-Espanol.md"]:
    if (ROOT.joinpath(rel).exists():
        text = read(rel).replace("v1.4.0", "v1.5.0")
        if "Centurion" not in text:
            text += "\n\n## PRO X 2 en v1.5.0\n\nLogitech PRO X 2 LIGHTSPEED usa Centurion HID directo para conocer el estado físico ON/OFF y el porcentaje de batería. El valor de configuración sigue siendo `LogitechGHub` por compatibilidad, pero ya no se usa la ruta eliminada `/battery/<deviceId>/state` de G HUB para detectar el estado del PRO X 2. Una lectura HID desconocida nunca cambia el audio y el apagado sigue necesitando varias observaciones confirmadas.\n"
        write(rel, text)


site = read("site/index.html").replace("v1.4.0", "v1.5.0")
site = site.replace("with a generic Windows endpoint mode, a Logitech PRO X family fallback through G HUB, and SteelSeries Arctis Nova 5/5X over HID.", "with a generic Windows endpoint mode, direct Logitech PRO X 2 Centurion HID with tray battery, G HUB fallback for other compatible Logitech headsets, and SteelSeries Arctis Nova 5/5X over HID.")
site = site.replace('<div class="card"><h3>Tray controls</h3><p class="muted">Pause switching, reconfigure endpoints and control Audio Enhancements without reinstalling.</p></div>', '<div class="card"><h3>Tray controls + battery</h3><p class="muted">Pause switching, reconfigure endpoints and control Audio Enhancements. PRO X 2 also shows live battery percentage and connection state.</p></div>')
site = site.replace("<h2>Two detection modes</h2>", "<h2>Detection providers</h2>")
site = site.replace('''      <div class="card">\n        <h3>LogitechGHub</h3>\n        <p class="muted">Fallback for Logitech PRO X 2, whose Windows endpoint can remain <code>Active</code> while the physical headset is off. G HUB's local WebSocket supplies the physical-state signal.</p>\n        <pre><code>payload present → ON\npayload absent  → OFF</code></pre>\n      </div>''', '''      <div class="card">\n        <h3>Logitech PRO X 2 · Centurion HID</h3>\n        <p class="muted">v1.5.0 reads the LIGHTSPEED receiver directly, restoring ON/OFF detection after G HUB changed its old battery route. The same direct reply supplies tray battery percentage.</p>\n        <pre><code>valid battery → ON + %\nknown power signature → OFF\nunknown → no switch</code></pre>\n      </div>\n      <div class="card">\n        <h3>LogitechGHub</h3>\n        <p class="muted">Other compatible Logitech headsets can still use G HUB's local WebSocket when Windows does not expose their physical state.</p>\n        <pre><code>payload present → ON\npayload absent  → OFF</code></pre>\n      </div>''')
site = site.replace("<li>Logitech G HUB only when the selected headset requires <code>LogitechGHub</code> mode.</li>", "<li>Logitech G HUB only for Logitech headsets that still use the G HUB provider; PRO X 2 direct state/battery is read from HID.</li>")
write("site/index.html", site)


sources = read("SOURCES.md").replace("Verified on August 7, 2026 (updated August 12, 2026).", "Verified on August 7, 2026 (updated August 31, 2026).")
old = '''## PRO X 2 specific evidence\n\nDuring the original AutoSwitch build, a controlled test was run on the target machine:\n\n- PRO X 2 on: `GET /battery/<deviceId>/state` returned a battery payload.\n- PRO X 2 off: several consecutive queries returned no payload.\n- PRO X 2 back on: the payload returned.\n\nThat behavior is the basis for the runtime's ON/OFF detection and must be re-verified if a G HUB update changes it.\n'''
new = '''## PRO X 2 specific evidence\n\nOriginal 2026-08-07 behavior:\n\n- PRO X 2 on: `GET /battery/<deviceId>/state` returned a battery payload.\n- PRO X 2 off: several consecutive queries returned no payload.\n- PRO X 2 back on: the payload returned.\n\nRegression observed on 2026-08-31 with G HUB `2026.5.939708`:\n\n- `/devices/list` still found the PRO X 2 and reported `state=ACTIVE` / `resourcesAvailable=true` both ON and OFF;\n- `GET /battery/dev00000000/state` returned `NO_SUCH_PATH`;\n- known G HUB subscriptions did not restore the removed battery route.\n\nDirect receiver validation on the same PRO X 2 (`VID 046D`, `PID 0AF7`):\n\n- vendor HID collection: UsagePage `0xFFA0`, Usage `0x0001`, 64-byte input/output;\n- a Centurion battery request returns a valid `0x51 0x0B ...` frame while connected, with battery percentage at byte 10;\n- physical OFF repeatedly produced `51 05 00 FF 03 1A 0B 00 ...`, followed by no valid battery response;\n- two complete real AutoSwitch cycles succeeded: OFF selected the configured fallback after two confirmed samples, and ON selected the PRO X 2 again;\n- battery values observed in the end-to-end run were 70% and 76%.\n\nPublic protocol cross-check: HeadsetControl's Logitech G PRO X 2 LIGHTSPEED implementation:\n\nhttps://github.com/Sapd/HeadsetControl/blob/master/lib/devices/logitech_gpro_x2_lightspeed.hpp\n\nThe project implementation additionally treats the exact OFF signature observed on the tested hardware as a confirmed disconnected observation. Any other missing/invalid response remains `Unknown` and never changes the output.\n'''
sources = once(sources, old, new, "SOURCES")
write("SOURCES.md", sources)

support = read("SUPPORT.md")
support = support.replace("- selected detection mode (`WindowsEndpoint` or `LogitechGHub`);", "- selected detection mode (`WindowsEndpoint`, `LogitechGHub` or `SteelSeriesNova5`) and, for PRO X 2, the direct HID state shown by `Verify.cmd`;")
support = support.replace("Compatibility cannot be guaranteed for every wireless headset. The universal path depends on the state Windows exposes; the Logitech PRO X 2 fallback depends on an unofficial local G HUB interface that Logitech may change.", "Compatibility cannot be guaranteed for every wireless headset. The universal path depends on the state Windows exposes. Starting in v1.5.0, PRO X 2 LIGHTSPEED uses its receiver directly through Centurion HID; other Logitech G HUB providers still depend on an unofficial local interface that Logitech may change.")
support += "\n## PRO X 2 after a G HUB update\n\nIf a PRO X 2 installation stopped switching after a G HUB update, install v1.5.0 or newer and run `Verify.cmd`. The verifier should report the direct Centurion HID provider plus `Connected`/`Disconnected` state and battery when available.\n"
write("SUPPORT.md", support)

security = read("SECURITY.md")
security = security.replace("### Logitech G HUB local WebSocket\n\n`ws://localhost:9010` is an undocumented, reverse-engineered local interface. It is **not** an official Logitech API. Treat responses as untrusted input and keep bounded connection/request/close timeouts.\n", "### Logitech direct HID / G HUB boundaries\n\nPRO X 2 LIGHTSPEED state and battery are read from the local `046D:0AF7` HID receiver through a narrowly scoped Centurion request. Treat malformed/unexpected frames as `Unknown`; they must never trigger an output change. The known OFF signature is still debounced before the fallback is selected.\n\n`ws://localhost:9010` remains an undocumented, reverse-engineered local interface for other Logitech providers. It is **not** an official Logitech API. Treat responses as untrusted input and keep bounded connection/request/close timeouts.\n")
write("SECURITY.md", security)

agent = read("AGENT.md")
agent += '''\n\n## v1.5.0 PRO X 2 Centurion provider (verified 2026-08-31)\n\nG HUB `2026.5.939708` stopped exposing the PRO X 2 `/battery/<deviceId>/state` route (`NO_SUCH_PATH`) while `/devices/list` remained `ACTIVE` even with the headset physically OFF. v1.5.0 therefore keeps `DetectionMode = LogitechGHub` for backward-compatible configs but automatically prefers `lib/LogitechProX2Centurion.psm1` when the configured device is a PRO X 2.\n\nVerified receiver details: Logitech `046D:0AF7`, UsagePage `0xFFA0`, Usage `0x0001`, 64-byte reports. Connected queries return a valid battery response; the tested OFF state repeatedly emitted `51 05 00 FF 03 1A 0B 00 ...`. Unrecognized/malformed/time-out results are `Unknown` and never switch. The existing outer OFF debounce remains mandatory.\n\nEnd-to-end hardware validation on 2026-08-31 completed two real OFF/ON cycles: two confirmed OFF observations selected the fallback and the next valid battery reply selected the PRO X 2. The same provider supplies battery percentage to the tray.\n'''
write("AGENT.md", agent)

docs = read("docs/INDEX.md")
docs = once(docs, "## Releases\n\n- [v1.2.5 release notes](RELEASE-NOTES-v1.2.5.md)\n", "## Releases\n\n- [v1.5.0 release notes](RELEASE-NOTES-v1.5.0.md)\n- [v1.2.5 release notes](RELEASE-NOTES-v1.2.5.md)\n", "docs index")
write("docs/INDEX.md", docs)

release_notes = '''# Audio AutoSwitch v1.5.0\n\nv1.5.0 restores reliable Logitech PRO X 2 LIGHTSPEED switching after a change in Logitech G HUB's undocumented local API, and adds live PRO X 2 battery information to the tray.\n\n## What happened\n\nG HUB `2026.5.939708` was observed returning `NO_SUCH_PATH` for `GET /battery/<deviceId>/state`, while `/devices/list` continued to report the PRO X 2 receiver as `ACTIVE` even with the headset physically powered off. That removed the physical-state signal used by v1.4.x.\n\n## What changed\n\nPRO X 2 LIGHTSPEED (`VID 046D`, `PID 0AF7`) now uses Logitech's Centurion HID protocol directly through UsagePage `0xFFA0` and 64-byte reports. A valid battery reply means Connected and includes battery percentage. The known OFF signature means a disconnected observation. Any HID/open/read/protocol error is Unknown and never changes output; OFF still requires consecutive confirmations.\n\nExisting `DetectionMode = LogitechGHub` configs remain compatible. The runtime automatically chooses Centurion for PRO X 2; other compatible Logitech headsets keep the G HUB provider.\n\n## Tray battery\n\nA connected PRO X 2 now shows connection state and battery, for example `Battery: 76%`. When powered off the tray shows Disconnected without a stale battery value.\n\n## Hardware validation\n\nOn August 31, 2026 the direct provider completed repeated real `ON → OFF → ON` cycles. OFF selected the configured fallback after two confirmed observations; ON selected the PRO X 2 again. Battery values of 70% and 76% were observed during the end-to-end run.\n\n## Included updates\n\n- direct PRO X 2 provider and diagnostic tool;\n- verifier direct-state/battery reporting;\n- installer direct-HID preference;\n- tray state/battery display;\n- Pester coverage;\n- deterministic v1.5.0 packaging;\n- README, Wiki source (English and Spanish), website, changelog, sources, support, security and maintainer docs updated.\n'''
write("docs/RELEASE-NOTES-v1.5.0.md", release_notes)

release_workflow = '''name: Publish v1.5.0\n\non:\n  push:\n    branches:\n      - main\n    paths:\n      - '.github/workflows/release-v1.5.0.yml'\n\npermissions:\n  contents: write\n\njobs:\n  release:\n    runs-on: ubuntu-latest\n    timeout-minutes: 15\n    steps:\n      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n        with:\n          fetch-depth: 0\n          persist-credentials: false\n\n      - name: Skip if release exists\n        id: existing\n        env:\n          GH_TOKEN: ${{ github.token }}\n        run: |\n          if gh release view v1.5.0 >/dev/null 2>&1; then\n            echo 'exists=true' >> "$GITHUB_OUTPUT"\n          else\n            echo 'exists=false' >> "$GITHUB_OUTPUT"\n          fi\n\n      - name: Repository quality checks\n        if: steps.existing.outputs.exists == 'false'\n        run: |\n          python3 scripts/check-repository.py\n          python3 scripts/check-language.py\n          bash scripts/run-gitleaks.sh\n\n      - name: Build deterministic release twice\n        if: steps.existing.outputs.exists == 'false'\n        run: |\n          bash scripts/build-release.sh 1.5.0\n          first="$(cut -d' ' -f1 dist/PROX2-AutoSwitch-v1.5.0.zip.sha256)"\n          first_copy="$(mktemp /tmp/autoswitch-v1.5.0.XXXXXX.zip)"\n          trap 'rm -f -- "${first_copy}"' EXIT\n          cp dist/PROX2-AutoSwitch-v1.5.0.zip "${first_copy}"\n          rm -f dist/*.zip dist/*.sha256\n          bash scripts/build-release.sh 1.5.0\n          second="$(cut -d' ' -f1 dist/PROX2-AutoSwitch-v1.5.0.zip.sha256)"\n          test "$first" = "$second"\n          cmp "${first_copy}" dist/PROX2-AutoSwitch-v1.5.0.zip\n          cmp dist/PROX2-AutoSwitch-v1.5.0.zip dist/Audio-AutoSwitch.zip\n\n      - name: Publish v1.5.0\n        if: steps.existing.outputs.exists == 'false'\n        env:\n          GH_TOKEN: ${{ github.token }}\n        run: |\n          gh release create v1.5.0 \\\n            dist/PROX2-AutoSwitch-v1.5.0.zip \\\n            dist/PROX2-AutoSwitch-v1.5.0.zip.sha256 \\\n            dist/Audio-AutoSwitch.zip \\\n            dist/Audio-AutoSwitch.zip.sha256 \\\n            --target "$GITHUB_SHA" \\\n            --title 'v1.5.0 — PRO X 2 direct HID + tray battery' \\\n            --notes-file docs/RELEASE-NOTES-v1.5.0.md\n'''
write(".github/workflows/release-v1.5.0.yml", release_workflow)

print("v1.5 documentation/release preparation OK")
